# $Id$

import unittest
from StringIO import StringIO
from itcc.molecule import xyz2pdb

test_in = ''' 1  19.0934
     1  C      3.666000    0.063000    0.085000     1
'''

test_out = '''HEADER generated by itcc
HETATM    1  C   UNK     1       3.666   0.063   0.085  1.00  0.00
END
'''

class TestXyz2pdb(unittest.TestCase):
    def test(self):
        ifile = StringIO(test_in)
        ofile = StringIO()
        xyz2pdb.xyz2pdb(ifile, ofile)
        self.assertEqual(ofile.getvalue(), test_out)

def _test():
    unittest.main()

if __name__ == '__main__':
    _test()

    


