#!/usr/bin/env python
# $Id$

import sys
import os.path
import itcc
from itcc.Molecule import rmsd, removepbc
from itcc.CCS2 import catordiff
from itcc.Torsionfit import parmfit
from itcc.Tinker import simpparam
from itcc.Tools import mtxyzrg

__revision__ = '$Rev$'

subscript = {'rmsd': (rmsd.main, 'RMSD'),
             'catordiff': (catordiff.main, 'cyclic alkane torsion diffrent'),
             'printefit': (parmfit.main, 'print efit'),
             'simpparam': (simpparam.main, 'simplify parameter'),
             'removepbc': (removepbc.main, 'remove PBC'),
             'mtxyzrg':   (mtxyzrg.main, 'multi tinker xyz file\'s Rg'),
             }

def help():
    basename = os.path.basename(sys.argv[0])

    print 'Version:', itcc.__version__
    print
    print 'Sub-commands:'
    keys = subscript.items()
    keys.sort()
    for key in keys:
        print '  %s %-9s  %s' % (basename, key[0], key[1][1])

def main():
    if len(sys.argv) == 1:
        help()
        sys.exit(0)

    key = sys.argv[1]

    if key in subscript:
        del sys.argv[0]
        subscript[key][0]()
    else:
        help()
        sys.exit(1)

if __name__ == '__main__':
    main()
