#!/usr/bin/env python
# $Id$

import sys
import os.path
import itcc
from itcc.Molecule import rmsd, removepbc
from itcc.CCS2 import catordiff, confsearch
from itcc.Torsionfit import parmfit
from itcc.Tinker import simpparam
from itcc.Tools import mtxyzrg, cmpxyztop

__revision__ = '$Rev$'

subscript = {
    'catordiff': (catordiff.main, 'cyclic alkane torsion diffrent'),
    'cmpxyztop': (cmpxyztop.main, 'Compare topology of two xyz files'),
    'confsearch': (confsearch.main, 'Conformational search'),
    'mtxyzrg':   (mtxyzrg.main, 'multi tinker xyz file\'s Rg'),
    'printefit': (parmfit.main, 'print efit'),
    'removepbc': (removepbc.main, 'remove PBC'),
    'rmsd': (rmsd.main, 'RMSD'),
    'simpparam': (simpparam.main, 'simplify parameter'),
    }

def help():
    basename = os.path.basename(sys.argv[0])

    print 'Version:', itcc.__version__
    print
    print 'Sub-commands:'
    keys = subscript.items()
    keys.sort()
    for key in keys:
        print '  %s %-10s  %s' % (basename, key[0], key[1][1])

def main():
    if len(sys.argv) == 1:
        help()
        sys.exit(0)

    key = sys.argv[1]

    if key in subscript:
        del sys.argv[0]
        subscript[key][0]()
    else:
        help()
        sys.exit(1)

if __name__ == '__main__':
    main()
