\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename itcc.info
@settitle ITCC Manual 0.2
@c %**end of header

@node Top, CCS2, (dir), (dir)
@top Manual of ITCC

Manual of ITCC

@menu
* CCS2::                        
* Torsionfit::                  

@end menu

@node CCS2, Torsionfit, Top, Top
@chapter CCS2

@section confsearch
use 'itcc confsearch' to invoke it.

@node Torsionfit,  , CCS2, Top
@chapter Torsionfit

@section get data from Gaussian result
use @file{src/torsionfit/getscandata.py}.



@bye
